#!/bin/sh

#dockerTagName $1 nodejs-build-1 or front-end-build
#dockerFile $2

if [ -n "$1" ] && [ -n "$2" ]; then
    docker build -t tradetech/morgan:$1 $2
else
    docker build -t tradetech/morgan:front-end-build ./../frontend_dockerbuilds/deployment/Dockerfile
fi
