#!/bin/sh

#copy of my git config 5/22/15

#git config --global user.name 'Morgan Heimbeck'
#git config --global user.email 'morgan@tradetech.net'
#git config --global core.autocrlf input
#git config --global merge.tool p4merge
#git config --global mergetool "p4merge" p4merge.path '/Applications/p4merge.app/Contents/MacOS/p4merge'
git config --global alias.cg 'config --global'
git cg color.ui true
git cg alias.lg 'log --oneline --decorate --all --graph'
git cg alias.sl 'stash list'
git cg alias.ss 'stash save'
git cg alias.sp 'stash pop'
git cg alias.br branch
git cg alias.cl 'config --local'
git cg alias.co checkout
git cg alias.ci commit
git cg alias.cm 'checkout master'
git cg alias.rb 'rebase master'
git cg alias.mg merge
git cg alias.s status
git cg alias.pr 'pull --rebase'

#git config --global rerere.enabled = true
#git config --global push.default = matching
